apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-catalog
  template:
    metadata:
      labels:
        app: product-catalog
    spec:
      containers:
      - name: product-catalog
        image: arshshaikh777/product-catalog:latest
        ports:
        - containerPort: 80
 
---
apiVersion: v1
kind: Service
metadata:
  name: product-catalog-service
spec:
  type: NodePort
  selector:
    app: product-catalog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30009