apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-processing
  template:
    metadata:
      labels:
        app: order-processing
    spec:
      containers:
      - name: order-processing
        image: arshshaikh777/order-processing:latest
        ports:
        - containerPort: 80
 
---
apiVersion: v1
kind: Service
metadata:
  name: order-processing-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008